# Generated by Django 4.1.1 on 2022-09-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile_pictures', verbose_name='Фото устройства'),
        ),
    ]
