# Generated by Django 4.1.1 on 2022-09-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_devices_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentals',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile_pictures', verbose_name='Фото рентала'),
        ),
    ]
